CREATE TABLE IF NOT EXISTS files
(
	id  INTEGER PRIMARY KEY,
	path   TEXT UNIQUE ON CONFLICT ABORT
);

CREATE TABLE IF NOT EXISTS nodes
(
	id INTEGER PRIMARY KEY,
	signature  TEXT UNIQUE ON CONFLICT FAIL,
	file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE,
	kind TEXT DEFAULT NULL ,
	anchor INTEGER DEFAULT NULL REFERENCES nodes(id) ON DELETE SET DEFAULT
);

CREATE TABLE IF NOT EXISTS edges
(
	id INTEGER PRIMARY KEY,
	source INTEGER NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
	target INTEGER NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
	kind TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS facts
(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	node INTEGER NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
	name TEXT NOT NULL,
	val  TEXT
);